'use strict';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const PROCESS_DATA_REQUEST = 'PROCESS_DATA_REQUEST';
export const PROCESS_DATA_SUCCESS = 'PROCESS_DATA_SUCCESS';
export const PROCESS_DATA_FAILURE = 'PROCESS_DATA_FAILURE';