export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const PROCESS_DATA_REQUEST = 'PROCESS_DATA_REQUEST';
export const PROCESS_DATA_SUCCESS = 'PROCESS_DATA_SUCCESS';
export const PROCESS_DATA_FAILURE = 'PROCESS_DATA_FAILURE';

export const USE_CANVAS_TOGGLE = 'USE_CANVAS_TOGGLE';

export const FONT_LOAD_REQUEST = 'FONT_LOAD_REQUEST';
export const FONT_LOAD_SUCCESS = 'FONT_LOAD_SUCCESS';
export const FONT_LOAD_FAILURE = 'FONT_LOAD_FAILURE';