export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const DELETE_DATA_ITEM = 'DELETE_DATA_ITEM';
export const ADD_DATA_ITEM = 'ADD_DATA_ITEM';
export const EDIT_DATA_ITEM = 'EDIT_DATA_ITEM';

export const TAGS_CLOUD_BUILD_REQUEST = 'TAGS_CLOUD_BUILD_REQUEST';
export const TAGS_CLOUD_BUILD_SUCCESS = 'TAGS_CLOUD_BUILD_SUCCESS';
export const TAGS_CLOUD_BUILD_FAILURE = 'TAGS_CLOUD_BUILD_FAILURE';
export const TAGS_CLOUD_REMOVE_TAG = 'TAGS_CLOUD_REMOVE_TAG';
export const INCREMENTAL_BUILD_TAGS_CLOUD_REQUEST = 'INCREMENTAL_BUILD_TAGS_CLOUD_REQUEST';
export const INCREMENTAL_BUILD_TAGS_CLOUD_SUCCESS = 'INCREMENTAL_BUILD_TAGS_CLOUD_SUCCESS';
export const INCREMENTAL_BUILD_TAGS_CLOUD_FAILURE = 'INCREMENTAL_BUILD_TAGS_CLOUD_FAILURE';
export const INCREMENTAL_BUILD_ADD_TAG_ID = 'INCREMENTAL_BUILD_ADD_TAG_ID';
export const INCREMENTAL_BUILD_REMOVE_TAG_ID = 'INCREMENTAL_BUILD_REMOVE_TAG_ID';

export const RESET_TAGS_CLOUD = 'RESET_TAGS_CLOUD';

export const USE_CANVAS_TOGGLE = 'USE_CANVAS_TOGGLE';

export const FONT_LOAD_REQUEST = 'FONT_LOAD_REQUEST';
export const FONT_LOAD_SUCCESS = 'FONT_LOAD_SUCCESS';
export const FONT_LOAD_FAILURE = 'FONT_LOAD_FAILURE';

export const ADD_RECT_AREAS_MAPS = 'ADD_RECT_AREAS_MAPS';
export const DELETE_RECT_AREA_MAP = 'DELETE_RECT_AREA_MAP';
