export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const DELETE_DATA_ITEM = 'DELETE_DATA_ITEM';
export const ADD_DATA_ITEM = 'ADD_DATA_ITEM';
export const EDIT_DATA_ITEM = 'EDIT_DATA_ITEM';

export const BUILD_CLOUD_REQUEST = 'BUILD_CLOUD_REQUEST';
export const BUILD_CLOUD_SUCCESS = 'BUILD_CLOUD_SUCCESS';
export const BUILD_CLOUD_FAILURE = 'BUILD_CLOUD_FAILURE';

export const RESET_TAGS_CLOUD = 'RESET_TAGS_CLOUD';

export const USE_CANVAS_TOGGLE = 'USE_CANVAS_TOGGLE';

export const FONT_LOAD_REQUEST = 'FONT_LOAD_REQUEST';
export const FONT_LOAD_SUCCESS = 'FONT_LOAD_SUCCESS';
export const FONT_LOAD_FAILURE = 'FONT_LOAD_FAILURE';
