export const TAGS_DATA_FETCH_REQUEST = 'TAGS_DATA_FETCH_REQUEST';
export const TAGS_DATA_FETCH_SUCCESS = 'TAGS_DATA_FETCH_SUCCESS';
export const TAGS_DATA_FETCH_FAILURE = 'TAGS_DATA_FETCH_FAILURE';
export const RESET_TAGS_DATA = 'RESET_TAGS_DATA';

export const TAGS_DATA_DELETE_DATA_ITEM = 'TAGS_DATA_DELETE_DATA_ITEM';
export const TAGS_DATA_ADD_DATA_ITEM = 'TAGS_DATA_ADD_DATA_ITEM';
export const TAGS_DATA_EDIT_DATA_ITEM = 'TAGS_DATA_EDIT_DATA_ITEM';
export const TAGS_DATA_DELETE_ALL_DATA = 'TAGS_DATA_DELETE_ALL_DATA';

export const TAGS_CLOUD_BUILD_REQUEST = 'TAGS_CLOUD_BUILD_REQUEST';
export const TAGS_CLOUD_BUILD_SUCCESS = 'TAGS_CLOUD_BUILD_SUCCESS';
export const TAGS_CLOUD_BUILD_FAILURE = 'TAGS_CLOUD_BUILD_FAILURE';
export const TAGS_CLOUD_BUILD_PROGRESS_UPDATE = 'TAGS_CLOUD_BUILD_PROGRESS_UPDATE';
export const TAGS_CLOUD_REMOVE_TAG = 'TAGS_CLOUD_REMOVE_TAG';
export const TAGS_CLOUD_UPDATE_TAG = 'TAGS_CLOUD_UPDATE_TAG';
export const TAGS_CLOUD_UPDATE_TAG_COLOR = 'TAGS_CLOUD_UPDATE_TAG_COLOR';
export const INCREMENTAL_BUILD_TAGS_CLOUD_REQUEST = 'INCREMENTAL_BUILD_TAGS_CLOUD_REQUEST';
export const INCREMENTAL_BUILD_TAGS_CLOUD_SUCCESS = 'INCREMENTAL_BUILD_TAGS_CLOUD_SUCCESS';
export const INCREMENTAL_BUILD_TAGS_CLOUD_FAILURE = 'INCREMENTAL_BUILD_TAGS_CLOUD_FAILURE';
export const INCREMENTAL_BUILD_ADD_TAG_ID = 'INCREMENTAL_BUILD_ADD_TAG_ID';
export const INCREMENTAL_BUILD_REMOVE_TAG_ID = 'INCREMENTAL_BUILD_REMOVE_TAG_ID';

export const RESET_TAGS_CLOUD = 'RESET_TAGS_CLOUD';

export const USE_CANVAS_TOGGLE = 'USE_CANVAS_TOGGLE';

export const FONT_LOAD_REQUEST = 'FONT_LOAD_REQUEST';
export const FONT_LOAD_SUCCESS = 'FONT_LOAD_SUCCESS';
export const FONT_LOAD_FAILURE = 'FONT_LOAD_FAILURE';
export const FONT_LOAD_RESET = 'FONT_LOAD_RESET';

export const RECT_AREAS_MAPS_ADD_MAPS = 'RECT_AREAS_MAPS_ADD_MAPS';
export const RECT_AREAS_MAPS_REMOVE_MAPS = 'RECT_AREAS_MAPS_REMOVE_MAPS';
export const RECT_AREAS_MAPS_RESET = 'RECT_AREAS_MAPS_RESET';

export const SETTINGS_UPDATE = 'SETTINGS_UPDATE';

export const NOTIFICATIONS_PUSH = 'NOTIFICATIONS_PUSH';
export const NOTIFICATIONS_POP = 'NOTIFICATIONS_POP';
export const NOTIFICATIONS_REPLACE = 'NOTIFICATIONS_REPLACE';
export const NOTIFICATIONS_DELETE = 'NOTIFICATIONS_DELETE';
